[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc_version = "0.8.24"

local = "http://127.0.0.1:8545"
remappings = [
     "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
     "@chainlink/contracts/=lib/chainlink/contracts/",
     "@solmate/=lib/solmate/src/",
]

[rpc_endpoints]
polygon_amoy = "https://rpc-amoy.polygon.technology"

[etherscan]
polygon_amoy = { key = "${POLYGONSCAN_API_KEY}", url = "https://api-amoy.polygonscan.com/api" }
