"use client";

import { useReadContract } from "wagmi";
import { CONTRACT_ADDRESSES, AIOracleABI } from "@/lib/contracts";

type Props = {
  contentHash?: string;
};

export default function AIAnalysisSection({ contentHash }: Props) {
  const { data: aiAnalysis, isLoading, error } = useReadContract({
    address: CONTRACT_ADDRESSES.Verification, // AI Oracle might be called through Verification
    abi: AIOracleABI,
    functionName: 'getAnalysis',
    args: contentHash ? [contentHash] : undefined,
    query: {
      enabled: !!contentHash,
    }
  });

  if (!contentHash) {
    return null;
  }

  if (isLoading) {
    return (
      <div className="mt-6 p-4 bg-blue-50 border border-blue-200 rounded-lg">
        <div className="flex items-center gap-2">
          <div className="animate-spin h-5 w-5 border-2 border-blue-600 border-t-transparent rounded-full"></div>
          <span className="text-blue-800 font-medium">Loading AI analysis...</span>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="mt-6 p-4 bg-yellow-50 border border-yellow-200 rounded-lg">
        <div className="flex items-start gap-2">
          <span className="text-xl">⚠️</span>
          <div>
            <h4 className="font-semibold text-yellow-800">AI Analysis Unavailable</h4>
            <p className="text-sm text-yellow-700 mt-1">
              The AI credibility analysis for this article is not yet available or failed to load.
            </p>
          </div>
        </div>
      </div>
    );
  }

  const credibilityScore = aiAnalysis ? Number(aiAnalysis) : 0;

  if (credibilityScore === 0) {
    return (
      <div className="mt-6 p-4 bg-gray-50 border border-gray-200 rounded-lg">
        <div className="flex items-start gap-2">
          <span className="text-xl">🤖</span>
          <div>
            <h4 className="font-semibold text-gray-800">AI Analysis Pending</h4>
            <p className="text-sm text-gray-600 mt-1">
              This article is queued for AI credibility analysis. Check back soon.
            </p>
          </div>
        </div>
      </div>
    );
  }

  const getScoreColor = (score: number) => {
    if (score >= 80) return "text-green-600";
    if (score >= 60) return "text-blue-600";
    if (score >= 40) return "text-yellow-600";
    return "text-red-600";
  };

  const getScoreBg = (score: number) => {
    if (score >= 80) return "bg-green-50 border-green-200";
    if (score >= 60) return "bg-blue-50 border-blue-200";
    if (score >= 40) return "bg-yellow-50 border-yellow-200";
    return "bg-red-50 border-red-200";
  };

  const getScoreLabel = (score: number) => {
    if (score >= 80) return "High Credibility";
    if (score >= 60) return "Moderate Credibility";
    if (score >= 40) return "Low Credibility";
    return "Very Low Credibility";
  };

  return (
    <div className={`mt-6 p-4 border rounded-lg ${getScoreBg(credibilityScore)}`}>
      <div className="flex items-start justify-between gap-4">
        <div className="flex items-start gap-3 flex-1">
          <span className="text-2xl">🤖</span>
          <div className="flex-1">
            <h4 className="font-semibold text-gray-800">AI Credibility Analysis</h4>
            <p className="text-sm text-gray-600 mt-1">
              Automated analysis powered by AI Oracle (Chainlink)
            </p>
          </div>
        </div>
        <div className="text-right">
          <div className={`text-4xl font-bold ${getScoreColor(credibilityScore)}`}>
            {credibilityScore}
          </div>
          <div className="text-sm text-gray-600">/ 100</div>
        </div>
      </div>
      
      <div className="mt-4">
        <div className="flex items-center justify-between text-xs text-gray-600 mb-1">
          <span>{getScoreLabel(credibilityScore)}</span>
          <span>{credibilityScore}%</span>
        </div>
        <div className="w-full bg-gray-200 rounded-full h-3">
          <div 
            className={`h-3 rounded-full transition-all ${
              credibilityScore >= 80 ? 'bg-green-600' :
              credibilityScore >= 60 ? 'bg-blue-600' :
              credibilityScore >= 40 ? 'bg-yellow-600' : 'bg-red-600'
            }`}
            style={{ width: `${credibilityScore}%` }}
          />
        </div>
      </div>

      <div className="mt-4 pt-4 border-t border-gray-300">
        <p className="text-xs text-gray-500">
          <strong>Note:</strong> This AI score is generated by analyzing content patterns, 
          source reliability, fact-checking databases, and linguistic indicators. It should 
          be used alongside human verification, not as the sole authority.
        </p>
      </div>
    </div>
  );
}
